# Generated by Django 2.2.1 on 2021-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateTimeField(null=True)),
                ('used_metric_value', models.IntegerField()),
                ('usage_type', models.CharField(default='', max_length=20)),
                ('subscriptions', models.ManyToManyField(to='subscriptions.Subscription')),
            ],
            options={
                'ordering': ('usage_date',),
            },
        ),
    ]
