# Generated by Django 2.2.1 on 2021-07-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_subscriptions', '0001_initial'),
        ('att_subscriptions', '0001_initial'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateTimeField(null=True)),
                ('usage_type', models.CharField(choices=[('voice', 'Voice'), ('data', 'Data')], default='', max_length=10)),
                ('used_metric_value', models.IntegerField()),
                ('att_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('sprint_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
            ],
            options={
                'ordering': ('usage_date',),
            },
        ),
    ]
